### ISSUE TITLE
Add class modifiers for GRID based on proportions - For example Bootstrap `.col-6` or `col-2`

### ISSUE THREAD

**Issue by Radek-Wawrzyk** [new-fantastic/fantastic-css#7]

**Comment by allozaur** [comment]
This is already handled by:

1. This Mixin — https://github.com/new-fantastic/fantastic-css/blob/master/src/layout/base/mixins/grid.scss
2. This Classes stylesheet — https://github.com/new-fantastic/fantastic-css/blob/master/src/layout/base/classes/grid.scss
